### ISSUE TITLE
可能的連結誤植

### ISSUE THREAD

**Issue by YuevUwU** [Edit-Mr/emtech#12]
很抱歉有些可能已在開發計劃中還拿出來提：
- 分類已在幾天前作出改動，導致首頁「網棧」與「Github Actions」的 `header-categories-item` 無效
- 「網栈，教學」使用简化字，~~容易被 Winst** **ng 罵~~
- `footer-social` 的 Github 圖標指向的是emblog的空存儲庫，而非實際開發的emtech，是否為刻意暫且未知

**Comment by Edit-Mr** [comment]
感謝提醒
emtech 是網站，emblog 是這個生成器，之後是希望把 emblog 整理成一個單獨的專案讓大家使用，把它弄成 submodule 或是弄成 npm

**Comment by Edit-Mr** [comment]
全形逗號是 bug，晚點修
